# Generated by Django 3.1 on 2021-02-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vive', '0002_auto_20210212_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='friend',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
