# Generated by Django 3.1 on 2021-02-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vive', '0003_auto_20210214_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(),
        ),
    ]
